[settings]
experimental = true

[tools]
deno = "latest"
go = "latest"
gcloud = "latest"
python = "latest"
node = "lts"
pnpm = "latest"
"aqua:uv" = "latest"
"aqua:snyk/cli" = "latest"
"npm:@antfu/ni" = "latest"
"aqua:biomejs/biome" = "latest"
"aqua:trivy" = "latest"
"aqua:dprint" = "0.49.1"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:cz-conventional-changelog" = "latest"
"npm:@aikidosec/safe-chain" = "latest"
